### ISSUE TITLE
The name is not activatable

### ISSUE THREAD

**Issue by IsaacWangTT** [damonto/telegram-sms#6]
### 问题
成功编译完 libqmi 和 lpac 后运行 Telegram-sms 2.0.3 版本，报错，后运行最新 CI (v2.0.3-35-gce1730e)，依旧，如下

``` shell
2024/07/29 12:07:11 INFO you are using version=v2.0.3-35-gce1730e
2024/07/29 12:07:11 WARN failed to scan devices error="The name is not activatable"
2024/07/29 12:07:11 ERROR failed to watch modems error="The name is not activatable"
panic: The name is not activatable

goroutine 35 [running]:
github.com/damonto/telegram-sms/internal/pkg/modem.(*Manager).watch(0x400010fae0)
    github.com/damonto/telegram-sms/internal/pkg/modem/manager.go:54 +0xc8
created by github.com/damonto/telegram-sms/internal/pkg/modem.NewManager in goroutine 1
    github.com/damonto/telegram-sms/internal/pkg/modem/manager.go:42 +0x128
```

### 系统版本
Arch Linux Arm (Linux alarm 6.9.12-2-aarch64-ARCH)

**Comment by damonto** [comment]
You must start ModemManager first.
